### ISSUE TITLE
수강 신청 버튼 표시

### ISSUE THREAD

**Issue by LeeSeungYun1020** [LeeSeungYun1020/Baleum#15]
수강 신청 버튼이 수강 중인 강의와 수강 종료한 강의에 표시되는 문제가 있음.

**Comment by gimume** [comment]
@LeeSeungYun1020 내가 수강 중인 강좌인지 확인하는 API 부탁드립니다!! 파라미터로 강좌 id보내면 true false 오는!!

**Comment by LeeSeungYun1020** [comment]
수강 전인지 확인할 수 있는 API(before taking class) #20 에 반영되었습니다.
