### ISSUE TITLE
수강 인증서에 QR코드, 사용자 이름이 표시되지 않음

### ISSUE THREAD

**Issue by LeeSeungYun1020** [LeeSeungYun1020/Baleum#28]
수강인증서에 표시되는 사용자 아이디만 표시됨. 이를 이름(아이디) 형식으로 변경 필요
우측에는 QR코드 추가가 필요
1. 서버에서 API 생성
2. 웹 수강인증서 페이지에 반영
3. 웹 QR코드 추가

**Comment by gimume** [comment]
#38 QR코드 추가 및 이름 형식 변경 완료
