### ISSUE TITLE
생성 강의 전송 방식

### ISSUE THREAD

**Issue by gimume** [LeeSeungYun1020/Baleum#33]
모든 컨텐츠를 입력한 후에 강의 등록해야 함
입력 포맷 형식을 맞춰야 함

**Comment by LeeSeungYun1020** [comment]
{ name: String, detail: String, category: String, image: String}
주의 사항: 카테고리는 기존 카테고리 중에 드롭다운으로 고를 수 있도록, 이미지는 base64 형식으로

**Comment by LeeSeungYun1020** [comment]
강의 컨텐츠 생성
1. create   
(한 번 등록한 강의는 수정 불가능하다는 사실을 알림)
2. update  
(기존 목록은 유지하고 강의 추가만 가능)  
3. delete  
(아예 강의 자체를 삭제)

**Comment by LeeSeungYun1020** [comment]
강의 컨텐츠
[{contentID, type, title, url}, ...]

**Comment by LeeSeungYun1020** [comment]
/class/create
{ name: String, detail: String, category: String, image: String}
/class/content/add
[{contentID, type, title, url}, ...]
/class/delete
{ classId: Int }

**Comment by LeeSeungYun1020** [comment]
사지선다는 #35 해결 이후 추가
컨텐츠 타입은 "강의", "시험" 두 가지가 있음
드롭다운으로 강의인지 시험인지 선택 가능해야 
강의인 경우 url이 들어가며
시험인 경우 4가지 선택지가 입력되어야 한다.
정답은 선택지 앞의 라디오 버튼으로 선택 가능하도록 구현되어야 한다.

**Comment by LeeSeungYun1020** [comment]
1차구현
새로운 강의 생성
/class/create
post 전송값 예시
```
{
  "name": "테스트 강의",
  "detail": "테스트 강의입니다.",
  "category": "투자",
  "image": "some"
}
```
성공시 반환값 예시
```
{
  "result": true,
  "classId": 24
}
```
/class/update
/class/delete

**Comment by LeeSeungYun1020** [comment]
2차 구현
강의 컨텐츠 추가
/class/contents/24/add
post 전송값 예시
```
[
  {
    "contentId": 1,
    "type": "영상",
    "title": "새로운 영상1",
    "url": "https://www.youtube.com/watch?v=wvQm3qf3CEo"
  },
  {
    "contentId": 2,
    "type": "영상",
    "title": "새로운 영상2",
    "url": "https://www.youtube.com/watch?v=wvQm3qf3CEo"
  },
  {
    "contentId": 3,
    "type": "영상",
    "title": "새로운 영상3",
    "url": "https://www.youtube.com/watch?v=wvQm3qf3CEo"
  }
]
```
